#the docker compose file version
version: "3.3"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  # service 1 named react-dev
  react-dev:
    # service 1 container name
    container_name: react-dev
    build:
      # the context (working directory) is the current directory
      # change this to the directory containing the dockerfile if in a different place
      context: ./client
      # the dockerfile to be run
      dockerfile: Dockerfile
    # map the exposed port from the underlying service to a port exposed to the outside
    # in this case  map port 3000 exposed by create react app to also 3000
    # to be used to access the container from the outside
    ports:
      - "3000:3000"
    # the mounted volumes (folders which are outside docker but being used by docker)
    volumes:
      - "./client/src:/app/src"
    # set the environment to development
    environment:
      - NODE_ENV=development
  db-service:
      container_name: db-service
      network_mode: host
      build:
        context: ./db-service
        dockerfile: dockerfile
      volumes:
        - "./db-service:/app"
      environment:
      - NODE_ENV=development
  smptp-service:
      container_name: smtp-service
      network_mode: host
      build:
        context: ./smtp-service
        dockerfile: dockerfile
      ports:
      - "5000:5000"
      volumes:
        - "./smtp-service:/app"
      environment:
      - NODE_ENV=development
  graphql-server:
      container_name: graphql-server
      network_mode: host
      build:
        context: ./server
        dockerfile: dockerfile
      ports:
      - "4000:4000"
      volumes:
        - "./server:/app"
      environment:
      - NODE_ENV=development